### ISSUE TITLE
Repository needs new host

### ISSUE THREAD

**Issue by redbassett** [nwillc/ksvg#9]
With the closure of Bintray, the old repository at `https://dl.bintray.com/nwillc/maven` is no longer available. Install instructions in #8 are no longer accurate, but cannot be updated until a new repository url is available.

**Comment by harry1453** [comment]
I've found a workaround:

1. `git clone https://github.com/nwillc/ksvg && cd ksvg`
2. `./gradlew build -x test`
3. Copy `ksvg-metadata-3.1.0-SNAPSHOT.jar`, `ksvg-js-3.1.0-SNAPSHOT.jar` and `ksvg-jvm-3.1.0-SNAPSHOT.jar` into new `libs` folder in your project root
4. Replace the following:
    1. `implementation("com.github.nwillc:ksvg-metadata:$ksvgVersion")` -> `implementation(files("libs/ksvg-metadata-3.1.0-SNAPSHOT.jar"))`
    2. `implementation("com.github.nwillc:ksvg-js:$ksvgVersion")` -> `implementation(files("libs/ksvg-js-3.1.0-SNAPSHOT.jar"))`
    3. `implementation("com.github.nwillc:ksvg-jvm:$ksvgVersion")` -> `implementation(files("libs/ksvg-jvm-3.1.0-SNAPSHOT.jar"))`

**Comment by redbassett** [comment]
Bumping this issue, @harry1453 suggests a valid way to manually add the binaries to a project, but I'm hoping @nwillc can get this re-hosted either on Maven Central or another artifact host!

**Comment by harry1453** [comment]
Perhaps `jitpack.io` could work?

**Comment by nwillc** [comment]
I’ve been away from jar ecosystem too long and initially tried but was pain

**Comment by harry1453** [comment]
@redbassett @nwillc I succeeded in getting `jitpack.io` to work! Please see #10.

You can use maven coordinate `com.github.harry1453.ksvg:ksvg:master-SNAPSHOT` to test that it works for you. You should only need the one coordinate for multiplatform.

**Comment by nwillc** [comment]
Merged - thanks!

**Comment by harryjph** [comment]
No problem! This can be closed now, I think

**Comment by redbassett** [comment]
It looks like this works for my needs just fine. Thank your @harry1453 for the implementation. I'm with @nwillc, this stuff is difficult to fix when you've been away from it for a while!
